name: Firebase CI/CD

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: pnpm install and build
              run: |
                  pnpm install --no-frozen-lockfile
                  pnpm build

            - name: Archive Build
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download Build
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: dist

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAMUDYATAMIR }}
                  channelId: live
                  projectId: pramudyatamir
